require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ProvidersController do

  def mock_provider(stubs={})
    @mock_provider ||= mock_model(Provider, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all providers as @providers" do
      Provider.stub(:all) { [mock_provider] }
      get :index
      assigns(:providers).should eq([mock_provider])
    end
  end

  describe "GET show" do
    it "assigns the requested provider as @provider" do
      Provider.stub(:find).with("37") { mock_provider }
      get :show, :id => "37"
      assigns(:provider).should be(mock_provider)
    end
  end

  describe "GET new" do
    it "assigns a new provider as @provider" do
      Provider.stub(:new) { mock_provider }
      get :new
      assigns(:provider).should be(mock_provider)
    end
  end

  describe "GET edit" do
    it "assigns the requested provider as @provider" do
      Provider.stub(:find).with("37") { mock_provider }
      get :edit, :id => "37"
      assigns(:provider).should be(mock_provider)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created provider as @provider" do
        Provider.stub(:new).with({'these' => 'params'}) { mock_provider(:save => true) }
        post :create, :provider => {'these' => 'params'}
        assigns(:provider).should be(mock_provider)
      end

      it "redirects to the created provider" do
        Provider.stub(:new) { mock_provider(:save => true) }
        post :create, :provider => {}
        response.should redirect_to(provider_url(mock_provider))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved provider as @provider" do
        Provider.stub(:new).with({'these' => 'params'}) { mock_provider(:save => false) }
        post :create, :provider => {'these' => 'params'}
        assigns(:provider).should be(mock_provider)
      end

      it "re-renders the 'new' template" do
        Provider.stub(:new) { mock_provider(:save => false) }
        post :create, :provider => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested provider" do
        Provider.stub(:find).with("37") { mock_provider }
        mock_provider.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :provider => {'these' => 'params'}
      end

      it "assigns the requested provider as @provider" do
        Provider.stub(:find) { mock_provider(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:provider).should be(mock_provider)
      end

      it "redirects to the provider" do
        Provider.stub(:find) { mock_provider(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(provider_url(mock_provider))
      end
    end

    describe "with invalid params" do
      it "assigns the provider as @provider" do
        Provider.stub(:find) { mock_provider(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:provider).should be(mock_provider)
      end

      it "re-renders the 'edit' template" do
        Provider.stub(:find) { mock_provider(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested provider" do
      Provider.stub(:find).with("37") { mock_provider }
      mock_provider.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the providers list" do
      Provider.stub(:find) { mock_provider }
      delete :destroy, :id => "1"
      response.should redirect_to(providers_url)
    end
  end

end
